tasks:
- before: pip install pipreqs && pipreqs && pip install -r requirements.txt 
- command: pip install pipreqs && pipreqs && pip install -r requirements.txt && streamlit run app.py 
- command: pip install pipreqs && pipreqs && pip install -r requirements.txt && streamlit run biderectional.py
- command: pip install pipreqs && pipreqs && pip install -r requirements.txt && streamlit run debank.py
- command: pip install pipreqs && pipreqs && pip install -r requirements.txt && streamlit run funding_checker.py
- command: pip install pipreqs && pipreqs && pip install -r requirements.txt && streamlit run lending_rates.py

ports:
- port: 8501
  onOpen: open-preview
- port: 8502
  onOpen: open-preview
- port: 8503
  onOpen: open-preview
- port: 8504
  onOpen: open-preview
- port: 8505
  onOpen: open-preview



