# enter in a 12 word seedphrase in textboxes in streamlit and display the phrase
# then take the phrase and get the adresses and private keys for said address using web3py
# then display the addresses and private keys in a table

import streamlit as st

import pandas as pd
import numpy as np
import web3
from web3 import Web3
from web3.middleware import geth_poa_middleware
from eth_account import Account

st.title('Seedphrase to Private Key and Address')

st.write('Enter in your 12 word seedphrase below and click the button to display the address and private key for the first account generated by the seedphrase')

w3 = Web3()
w3.eth.account.enable_unaudited_hdwallet_features()

# w1 = st.text_input('Enter in the first word of your seedphrase')
# w2 = st.text_input('Enter in the second word of your seedphrase')
# w3 = st.text_input('Enter in the third word of your seedphrase')
# w4 = st.text_input('Enter in the fourth word of your seedphrase')
# w5 = st.text_input('Enter in the fifth word of your seedphrase')
# w6 = st.text_input('Enter in the sixth word of your seedphrase')
# w7 = st.text_input('Enter in the seventh word of your seedphrase')
# w8 = st.text_input('Enter in the eighth word of your seedphrase')
# w9 = st.text_input('Enter in the ninth word of your seedphrase')
# w10 = st.text_input('Enter in the tenth word of your seedphrase')
# w11 = st.text_input('Enter in the eleventh word of your seedphrase')
# w12 = st.text_input('Enter in the twelfth word of your seedphrase')
# b1 = st.button('Generate Address and Private Key')


seedphrase = "parent twenty hockey pen profit upon exhaust awful box exit good cash"

b1 = st.button('Generate Address and Private Key')

if b1:
    # seedphrase = w1 + ' ' + w2 + ' ' + w3 + ' ' + w4 + ' ' + w5 + ' ' + w6 + ' ' + w7 + ' ' + w8 + ' ' + w9 + ' ' + w10 + ' ' + w11 + ' ' + w12
    seedphrase = seedphrase
    account = Account.from_mnemonic(seedphrase)
    address = account.address
    private_key = account.privateKey
    st.write('Address:', address)
    # st.write('Private Key:', private_key)
    st.write('Seedphrase:', seedphrase)

    # convert private key to hex
    private_key_hex = private_key.hex()
    st.write('Private Key Hex:', private_key_hex)
    # show the other 9 addresses and private keys
    st.write('The other 9 addresses and private keys are:')
    for i in range(1, 10):
        account = Account.from_mnemonic(seedphrase, account_path="m/44'/60'/0'/0/" + str(i))
        address = account.address
        private_key = account.privateKey
        st.write('Address:', address)
        # st.write('Private Key:', private_key)
        # show private key in hex
        private_key_hex = private_key.hex()
        st.write('Private Key Hex:', private_key_hex)


